# This file contains advanced configuration options for a Zerynth project
# 
# Under the section "config" a list of options can be specified and activated;
# such options change the way Python and C modules are compiled.
#
# If you are using "ztc project" commands to compile, uplink, etc... please
# fill the sections target and specs with the required information
#

target: your_target_device_here
specs:
    port: your_device_port_here
    probe: your_jtag_probe_here
config: {}



